name: 'JavaScript for eval()'
description: 'JavaScript for eval()'
inputs:
  script:  # id of input
    description: 'JavaScript for eval()'
    required: true
outputs:
  stdout: # id of output
    description: 'Standard output from eval()'
runs:
  using: 'node16'
  main: 'dist/index.js'
